spring.application.name=booking-service
server.port=${PORT:8084}
spring.config.import=optional:file:../.env[.properties]

# Database
spring.datasource.url=${DB_URL_BOOKING}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

sports-service.url=${SPORTS_SERVICE_URL:http://localhost:8083}
notification-service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8085}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT (same secret as auth-service to validate tokens)
application.security.jwt.secret-key=${JWT_SECRET_KEY}

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
